FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore src/Workers/Ecommerce.Messaging.Worker/Ecommerce.Messaging.Worker.csproj
RUN dotnet publish src/Workers/Ecommerce.Messaging.Worker/Ecommerce.Messaging.Worker.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Ecommerce.Messaging.Worker.dll"]
