FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Gateway/Ecommerce.Gateway/Ecommerce.Gateway.csproj", "src/Gateway/Ecommerce.Gateway/"]
RUN dotnet restore "src/Gateway/Ecommerce.Gateway/Ecommerce.Gateway.csproj"

COPY . .
RUN dotnet publish "src/Gateway/Ecommerce.Gateway/Ecommerce.Gateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Ecommerce.Gateway.dll"]
