// <auto-generated />
using System;
using Ecommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Address", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Country")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("PostalCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Region")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UserAddress")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Ecommerce.Domain.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ecommerce.Domain.Country", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Iso2")
                        .HasColumnType("text");

                    b.Property<string>("Iso3")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Ecommerce.Domain.Image", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ProductId")
                        .IsRequired()
                        .HasColumnType("INT");

                    b.Property<string>("PublicCode")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Ecommerce.Domain.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BuyerName")
                        .HasColumnType("text");

                    b.Property<string>("BuyerUserName")
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("OrderAddressId")
                        .HasColumnType("INT");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceTax")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<string>("ShippingOperator")
                        .HasColumnType("text");

                    b.Property<string>("StripeApiKey")
                        .HasColumnType("text");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<int?>("WeightOrder")
                        .HasColumnType("INT");

                    b.Property<int>("orderStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Domain.OrderAddress", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Country")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("PostalCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Region")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UserAddress")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("OrderAddresses");
                });

            modelBuilder.Entity("Ecommerce.Domain.OrderItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("OrderId")
                        .HasColumnType("INT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INT");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("productName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Domain.ParTaxItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("MontoItem")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INT");

                    b.Property<string>("TaxName")
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxPercentage")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<decimal?>("TotalMontoItem")
                        .HasColumnType("DECIMAL(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("parTaxItems");
                });

            modelBuilder.Entity("Ecommerce.Domain.Product", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BarCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("INT");

                    b.Property<string>("CountrySell")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Currency")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("Price")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("ProductDimensionId")
                        .HasColumnType("INT");

                    b.Property<string>("ProductName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("PurchaseCriteria")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseLeadTime")
                        .HasColumnType("INT");

                    b.Property<string>("PurchaseLeadTimeUnit")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("PurchaseLot")
                        .HasColumnType("INT");

                    b.Property<string>("QrCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("Rating")
                        .HasColumnType("INT");

                    b.Property<int?>("RatingTotal")
                        .HasColumnType("INT");

                    b.Property<string>("ReplenishmentPoint")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("SafetyStock")
                        .HasColumnType("INT");

                    b.Property<string>("SellerName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("Stock")
                        .HasColumnType("INT");

                    b.Property<string>("UnitToBuy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UnitToProduction")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UnitToSell")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UnitToStore")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("typeProduct")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductDimension", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("INT");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductDimensions");
                });

            modelBuilder.Entity("Ecommerce.Domain.Review", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INT");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("INT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INT");

                    b.Property<decimal?>("TotalShipping")
                        .HasColumnType("DECIMAL(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("shippings");
                });

            modelBuilder.Entity("Ecommerce.Domain.ShippingOperator", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("INT");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("NameService")
                        .HasColumnType("text");

                    b.Property<string>("NameShippingOperator")
                        .HasColumnType("text");

                    b.Property<bool?>("OperatorStatus")
                        .HasColumnType("boolean");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TarifaShipping")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("shippingOperators");
                });

            modelBuilder.Entity("Ecommerce.Domain.ShoppingCart", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<Guid?>("ShoppingCartMasterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Ecommerce.Domain.ShoppingCartItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(20,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("ProductPicture")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("INT");

                    b.Property<Guid?>("ShoppingCartMasterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Ecommerce.Domain.Tax", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int>("ApplicationTax")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("INT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Taxs");
                });

            modelBuilder.Entity("Ecommerce.Domain.TaxByProduct", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("INT");

                    b.Property<int?>("TaxId")
                        .HasColumnType("INT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("Id")
                        .HasColumnType("INT");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("ProductId", "TaxId");

                    b.HasIndex("TaxId");

                    b.ToTable("TaxByProducts");
                });

            modelBuilder.Entity("Ecommerce.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("RoleId")
                        .HasColumnType("character varying(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Image", b =>
                {
                    b.HasOne("Ecommerce.Domain.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Order", b =>
                {
                    b.HasOne("Ecommerce.Domain.OrderAddress", "OrderAddress")
                        .WithMany()
                        .HasForeignKey("OrderAddressId");

                    b.Navigation("OrderAddress");
                });

            modelBuilder.Entity("Ecommerce.Domain.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.ParTaxItem", b =>
                {
                    b.HasOne("Ecommerce.Domain.Order", null)
                        .WithMany("ParTaxItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ecommerce.Domain.Product", b =>
                {
                    b.HasOne("Ecommerce.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Domain.ProductDimension", b =>
                {
                    b.HasOne("Ecommerce.Domain.Product", "product")
                        .WithOne("ProductDimension")
                        .HasForeignKey("Ecommerce.Domain.ProductDimension", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Review", b =>
                {
                    b.HasOne("Ecommerce.Domain.Product", "product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping", b =>
                {
                    b.HasOne("Ecommerce.Domain.ShippingOperator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("Ecommerce.Domain.Order", null)
                        .WithOne("Shipping")
                        .HasForeignKey("Ecommerce.Domain.Shipping", "OrderId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Ecommerce.Domain.ShippingOperator", b =>
                {
                    b.HasOne("Ecommerce.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Ecommerce.Domain.ShoppingCartItem", b =>
                {
                    b.HasOne("Ecommerce.Domain.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Ecommerce.Domain.Tax", b =>
                {
                    b.HasOne("Ecommerce.Domain.Country", "Country")
                        .WithMany("Taxes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Ecommerce.Domain.TaxByProduct", b =>
                {
                    b.HasOne("Ecommerce.Domain.Product", "Product")
                        .WithMany("TaxByProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.Tax", "Tax")
                        .WithMany("TaxByProducts")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ecommerce.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ecommerce.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ecommerce.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Domain.Country", b =>
                {
                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("Ecommerce.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ParTaxItems");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("Ecommerce.Domain.Product", b =>
                {
                    b.Navigation("ProductDimension");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("TaxByProducts");
                });

            modelBuilder.Entity("Ecommerce.Domain.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("Ecommerce.Domain.Tax", b =>
                {
                    b.Navigation("TaxByProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
